### ISSUE TITLE
Initial Release Checklist

### ISSUE THREAD

**Issue by ericziethen** [ericziethen/ezscrape#18]
- [x] Ensure all Module Trees Can be imported absolute (import in __init__.py)
- [x] All Tests passing
- [x] No Linting Issues
- [x] Readme and Changelog Created
- [x] Running on Windows
- [x] Running on Linux
- [x] Running with Latest Modules
- [x] Latest modules in frozen Requirements
- [x] Readme is Complete and shows build status
- [x] Test Coverage at least xx %
- [x] Ensure License, Readme & Changelog up to date
- [x] Ensure License, Readme & Changelog distributed with package if needed
